name: Automate Maintenance
on:
  pull_request_target:
    types:
      - opened
      - closed
      - synchronize

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        if: github.event.action == 'opened'
        env:
          PROJECT_ID: PN_kwHOAEwOmM4ABprK
        with:
          github-token: ${{ secrets.PROJECT_PAT  }}
          # THIS SCRIPT SHOULD BE INLINED AND NOT IN REPO
          # DUE TO THE TOKEN PERMISSIONS THAT ARE GIVEN
          # TO THE WORKFLOW. THIS SCRIPT WILL AND SHOULD
          # RUN FROM THE BASE REPO ALL TIMES.
          script: |
            const prLookup = await github.graphql(`
              query($owner: String!, $repo: String!, $number: Int!){
                repository(owner: $owner, name: $repo) {
                  pullRequest(number: $number) {
                    id
                  }
                }
              }
            `, context.issue);

            await github.graphql(`
              mutation($projectId: ID!, $contentId: ID!) {
                addProjectNextItem(input: {
                  projectId: $projectId,
                  contentId: $contentId,
                }) {
                  projectNextItem {
                    id
                  }
                }
              }
            `, {
              projectId: process.env.PROJECT_ID,
              contentId: prLookup.repository.pullRequest.id
            })
